version: "3"
services:
  client:
    image: todo-app
    build:
      context: ./todo-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  server:
    image: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"